version=1.0.1
build=2
downloadUrl=https://github.com/Expeditionaryrealmsteam/commissionsupdates/releases/download/v1.0.1/Commissions.jar
sha256=FBCDCB5E97E0A9B4FA348A5B4ADC4DFE12A11999D641163BEFE658EDEC34BFEA
