version=1.0.1
build=2
downloadUrl=https://github.com/Expeditionaryrealmsteam/commissionsupdates/releases/download/v1.0.1/Commissions.jar
sha256=391CDE4451E32293195714F97565D8CFB70A3EEF94EEC30A728FEB61B38BE73D
